name: Assignment-2 Workflow that deploys an application

on: 
  push: #it checks immediately after I push, before the code is considered safe to merge or deploy
    paths:
      - 'Assignment-2/**' # Only runs this workflow when something inside the Task-1 directory changes.
# '**' means anything inside Task-1, including files in subdirectories.

jobs:
  build:
    runs-on: ubuntu-latest # Fresh Ubuntu runner

    defaults:
      run: 
        working-directory: Assignment-2


    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Downloads repository contents to the runner

      - name: Build Docker Image
        id: buildAndPushImage 
        uses: dockerhub/ismailsdocker1/assignment-2:v1
        with:
          registry_url: 'docker.io'
          repository_name: 'ismailsdocker1/assignment-2'
          user_name: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          image_version: 'v1.0'
          docker_file: '.' 
      - name: Get pre step result output image_pull_url
        run: echo "The time was ${{ steps.buildAndPushImage.outputs.image_pull_url }}"