name: Assignment-2 Workflow that deploys an application

on: 
  push: #it checks immediately after I push, before the code is considered safe to merge or deploy
    paths:
      - 'Assignment-2/**' # Only runs this workflow when something inside the Task-1 directory changes.
# '**' means anything inside Task-1, including files in subdirectories.

jobs:
  build:
    runs-on: ubuntu-latest # Fresh Ubuntu runner

    defaults:
      run: 
        working-directory: Assignment-2


    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Downloads repository contents to the runner
