name: Assignment-2 Workflow that deploys an application

on: 
  push: #it checks immediately after I push, before the code is considered safe to merge or deploy
    paths:
      - 'Assignment-2/**' # Only runs this workflow when something inside the Task-1 directory changes.
# '**' means anything inside Task-1, including files in subdirectories.

jobs:
  build:
    runs-on: ubuntu-latest # Fresh Ubuntu runner

    defaults:
      run: 
        working-directory: Assignment-2


    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Downloads repository contents to the runner

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}


      - name: Build Docker image
        run: docker build -t ismailsdocker1/assignment-2:v1.0 .

      - name: Push Docker image
        run: docker push ismailsdocker1/assignment-2:v1.0

      - name: Run Docker container
        run: docker run -d -p 5002:5002 ismailsdocker1/assignment-2:v1.0




        # To see it at http://127.0.0.1:5002 yourself, the container needs to be running on my machine. That means after the workflow pushes the image to Docker Hub, I have to separately run it on my laptop. To do that do these commands below
        # docker pull ismailsdocker1/assignment-2:v1.0
# docker run -d -p 5002:5002 ismailsdocker1/assignment-2:v1.0