name: Task-1 Terraform Linting and Validating Pipeline

on: 
  push: #it checks immediately after I push, before the code is considered safe to merge or deploy
    paths:
      - 'Task-1/**' # Only runs this workflow when something inside the Task-1 directory changes.
# '**' means anything inside Task-1, including files in subdirectories.
jobs:
  lint-and-validate: # Single job because all checks use the same environment

    runs-on: ubuntu-latest # Fresh Ubuntu runner

    defaults:
      run: 
        working-directory: Task-1


    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Downloads repository contents to the runner

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v4 # Installs Terraform CLI

      - name: Terraform Init
        run: terraform init # Downloads providers/modules and prepares the Terraform working directory

      - name: Terraform Validate  
        run: terraform validate # Verifies the Terraform configuration is valid and Fails the job if syntax or configuration issues are found. Basically can Terraform read itB

      - name:  Set-up Terraform Lint 
        uses: terraform-linters/setup-tflint@v6.0.0

      - name: Terraform Lint 
        run: tflint # tflint checks to see if my terraform code is in line with terraform code best practices, so that also means that just because tflint picks up an error that doesn't necessarily mean it doesn't work.
        #